[package]
name = "ina"
version = "1.0.0"
authors = ["Paweł Osikowski"]
edition = "2018"

[dependencies]
arr_macro = "0.1.3"
fastrand = "1.4.1"

[build-dependencies]
chrono = "0.4.19"

[dev-dependencies]
criterion = "0.3.4"