[package]
name = "inanis"
version = "1.2.0"
authors = ["Pawel Osikowski"]
repository = "https://github.com/Tearth/Inanis"
edition = "2021"

[lib]
doctest = false

[dependencies]
fastrand = { version = "1.8.0" }
chrono = { version = "0.4.22" }
bitflags = { version = "1.3.2" }
prettytable-rs = { version = "0.9.0" }
shakmaty = { version = "0.21.1" }
shakmaty-syzygy = { version = "0.19.0" }

[build-dependencies]
chrono = { version = "0.4.22" }

[dev-dependencies]
criterion = { version = "0.3.6", features = ["html_reports"] }

[profile.release]
panic = "abort"
lto = true
strip = true
debug = false

[[bench]]
name = "evaluation_benchmark"
harness = false

[[bench]]
name = "fen_benchmark"
harness = false

[[bench]]
name = "perft_benchmark"
harness = false

[[bench]]
name = "see_benchmark"
harness = false