[package]
name = "inanis"
version = "1.1.0"
authors = ["Pawel Osikowski"]
repository = "https://github.com/Tearth/Inanis"
edition = "2021"

[lib]
doctest = false

[dependencies]
arr_macro = { version = "0.1.3" }
fastrand = { version = "1.7.0" }
chrono = { version = "0.4.19" }
bitflags = { version = "1.3.2" }
prettytable-rs = { version = "0.8.0" }
nameof = { version = "1.2.2" }
crossbeam = { version = "0.8.1" }

[build-dependencies]
chrono = { version = "0.4.19" }

[dev-dependencies]
criterion = { version = "0.3.5", features = ["html_reports"] }

[profile.release]
panic = "abort"
lto = true
debug = false

[[bench]]
name = "perft_benches"
harness = false