on:
  release:
    types:
      - created
env:
  CRATE_NAME: inanis
  OUTPUT_NAME: inanis
jobs:
  build_release:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Windows 32-bit x86
            target: i686-pc-windows-gnu
            output: windows_32bit_x86
            extension: .exe
            
          - name: Windows 64-bit x86-64
            target: x86_64-pc-windows-gnu
            output: windows_64bit_x86-64
            extension: .exe
            
          - name: Windows 64-bit x86-64 POPCNT
            target: x86_64-pc-windows-gnu
            output: windows_64bit_x86-64_popcnt
            features: +popcnt
            extension: .exe
            
          - name: Windows 64-bit x86-64 POPCNT BMI2
            target: x86_64-pc-windows-gnu
            output: windows_64bit_x86-64_popcnt_bmi2
            features: +popcnt,+bmi1,+bmi2
            extension: .exe
            
          - name: Linux 32-bit x86
            target: i686-unknown-linux-musl
            output: linux_32bit_x86
            
          - name: Linux 64-bit x86-64
            target: x86_64-unknown-linux-musl
            output: linux_64bit_x86-64
            
          - name: Linux 64-bit x86-64 POPCNT
            target: x86_64-unknown-linux-musl
            output: linux_64bit_x86-64_popcnt
            features: +popcnt
            
          - name: Linux 64-bit x86-64 POPCNT BMI2
            target: x86_64-unknown-linux-musl
            output: linux_64bit_x86-64_popcnt_bmi2
            features: +popcnt,+bmi1,+bmi2
            
          - name: Linux 32-bit ARM
            target: arm-unknown-linux-musleabi
            output: linux_32bit_arm
            
          - name: Linux 64-bit AArch64
            target: aarch64-unknown-linux-musl
            output: linux_64bit_aarch64
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: rustc
          args: --release --bin inanis --target=${{ matrix.target }} -- -C target-feature=${{ matrix.features }}
          use-cross: true
      - uses: thebongy/version-check@v1
        with:
          file: Cargo.toml
          tagFormat: ${version}
        id: version_check
      - run: mv target/${{ matrix.target }}/release/${{ env.CRATE_NAME }}${{ matrix.extension }} ${{ env.CRATE_NAME }}${{ matrix.extension }}
      - run: mv misc/${{ env.CRATE_NAME }}.bmp ${{ env.CRATE_NAME }}.bmp
      - run: zip ${{ env.OUTPUT_NAME }}_${{ steps.version_check.outputs.releaseVersion }}_${{ matrix.output }}.zip ${{ env.CRATE_NAME }}${{ matrix.extension }} ${{ env.OUTPUT_NAME }}.bmp LICENSE.md
      - uses: JasonEtco/upload-to-release@master
        with:
          args: ${{ env.OUTPUT_NAME }}_${{ steps.version_check.outputs.releaseVersion }}_${{ matrix.output }}.zip application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}